# Generated by Django 3.1 on 2022-10-12 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_ipam', '0002_auto_20221012_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'verbose_name': '网络地址表', 'verbose_name_plural': '网络地址表'},
        ),
        migrations.AlterModelOptions(
            name='subnet',
            options={'verbose_name': '网段表', 'verbose_name_plural': '网段表'},
        ),
    ]
