# Generated by Django 4.1.2 on 2022-10-12 17:01

import cidrfield.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_ipam', '0004_auto_20221012_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='描述信息'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='subnet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_ipam.subnet', verbose_name='子网段'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='master_subnet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_subnet_set', to='open_ipam.subnet', verbose_name='上一级子网段'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='subnet',
            field=cidrfield.models.IPNetworkField(db_index=True, verbose_name='子网段'),
        ),
    ]
