# Generated by Django 4.1.2 on 2022-10-12 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_ipam', '0005_alter_ipaddress_description_alter_ipaddress_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BgBu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='业务线名称')),
            ],
            options={
                'verbose_name': '业务线表',
                'verbose_name_plural': '业务线表',
                'db_table': 'bgbu',
            },
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='subnet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_ipam.subnet', verbose_name='归属子网段'),
        ),
        migrations.AddIndex(
            model_name='bgbu',
            index=models.Index(fields=['name'], name='bgbu_name_7454a1_idx'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='bgbu',
            field=models.ManyToManyField(blank=True, to='open_ipam.bgbu'),
        ),
    ]
