# Generated by Django 4.1.2 on 2022-10-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_ipam', '0006_bgbu_alter_ipaddress_subnet_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subnet',
            options={'verbose_name': '子网网段表', 'verbose_name_plural': '子网网段表'},
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='editDate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='lastDiscovery',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='lastOnlineTime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='lastScan',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
