# Generated by Django 4.1.2 on 2022-10-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_ipam', '0007_alter_subnet_options_ipaddress_editdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='freehosts_percent',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='空闲率'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='mask',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='editDate',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='编辑时间'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='lastOnlineTime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最近在线时间'),
        ),
    ]
