# Generated by Django 4.1.2 on 2022-10-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_ipam', '0008_ipaddress_freehosts_percent_ipaddress_mask_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaddress',
            name='freehosts_percent',
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='mask',
        ),
        migrations.AddField(
            model_name='subnet',
            name='freehosts_percent',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='空闲率'),
        ),
        migrations.AddField(
            model_name='subnet',
            name='mask',
            field=models.IntegerField(default=24),
        ),
    ]
